### ISSUE TITLE
Problem of pure virtual functions

### ISSUE THREAD

**Issue by obspsr** [fiz1962/INDI-Client#1]
I was surprised but it work before ;-)
mainwindow.cpp:30: error: invalid new-expression of abstract class type 'INDIClientDlg'
     myClient\* dlg = new INDIClientDlg();

indiclientdlg.h:9: note:   because the following virtual functions are pure within 'INDIClientDlg':
 class INDIClientDlg : public QObject, public INDI::BaseClient
If you have a moment, could you suggest your approach for fixing the problem,
I am not enough fluent in C++ <--> QT4 or 5 to subclass correctly the base class ...
Thanks for coop !
Best regards,
Serge

**Comment by fiz1962** [comment]
I'm not sure what the problem is.  Just downloaded a fresh copy from github and compiled/ran in Qt 5.7.0 and QT Creator 4.0.3.  Only had to change the library path in INDIClient.pro to match the new location of the wsock32 lib as shown below.  One other problem may be if you are trying to use a newer version of the INDI code.  This was written for 0.9.6.

My new config below.  May need to edit path depending on your system.

win32:CONFIG(release, debug|release): LIBS += -L$$PWD/../../../../../Qt/Tools/mingw530_32/i686-w64-mingw32/lib/ -llibwsock32
else:win32:CONFIG(debug, debug|release): LIBS += -L$$PWD/../../../../../Qt/Tools/mingw530_32/i686-w64-mingw32/lib/ -llibwsock32
else:unix: LIBS += -L$$PWD/../../../../../Qt/Qt5.0.1/Tools/MinGW/i686-w64-mingw32/ -l/usr/lib64/libz.a

**Comment by obspsr** [comment]
```
OOPs !

I am pretty sure, it's a problem of virtual functions use, due to
the fact that
you don't address them via pointers and a subclassed INDIClientDlg 

Older g++ permitted this sort of statement :
myClient = new INDIClientDlg();

...two years ago, but no more with g++ (GCC) 4.9.2 

for a while we must code things like:

myClient *otherClient = new INDIClientDlg();
...

mainwindow.cpp: In member function ‘void
MainWindow::on_pbConnect_clicked()’:
mainwindow.cpp:31: error: cannot allocate an object of abstract type
‘INDIClientDlg’
indiclientdlg.h:11: note:   because the following virtual functions
are pure within ‘INDIClientDlg’:
/usr/local/include/libindi/indibase.h:85: note:     virtual void
INDI::BaseMediator::removeDevice(INDI::BaseDevice*)
make: *** [mainwindow.o] Error 1

what do you think about this way ? ...

Thanks for coop,
Serge.
```

**Comment by fiz1962** [comment]
The problem seems to be at line #85 in indibase.h.  The following was inserted sometime after IndiLib v1.0.0 and v1.2.0.

virtual void removeDevice(INDI::BaseDevice *dp)  =0;

This is the line causing the problem and was not in ver 0.9.6 which this code was based on.  You seem to be compiling against some version in /usr/local/include/libindi.
